name: 'enterprise_data_platform'
version: '1.0.0'
config-version: 2

profile: 'enterprise_data_platform'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  start_date: '2020-01-01'
  end_date: '2030-12-31'
  default_currency: 'USD'

models:
  enterprise_data_platform:
    staging:
      +materialized: view
      +schema: staging
      +tags: ['staging']
    intermediate:
      +materialized: table
      +schema: intermediate
      +tags: ['intermediate']
    marts:
      +materialized: table
      +schema: marts
      +tags: ['marts', 'gold']

seeds:
  enterprise_data_platform:
    +schema: seeds

tests:
  enterprise_data_platform:
    +severity: warn
    +store_failures: true
